### ISSUE TITLE
Warning: Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by stefanedberg** [scaleway/action-scw#12]
Hi!

Github Actions warns about Node.js 16 when using scaleway/action-scw@v0.

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: scaleway/action-scw@v0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by remyleone** [comment]
We just pushed a v0 and v0.0.2 tag to the latest release. Could you test it out and say if it works for you?

**Comment by stefanedberg** [comment]
I can confirm that the warning is gone and that the action works as expected. Thanks for quick fix! 💯
